### ISSUE TITLE
Improve ranking for rollups and merges

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/thanks#12]
Rollups are vital to the project and we should recognize them in thanks, but the current algorithm counts them in a weird way. At the moment we count each merge commit included in the rollup, but that gives rollup makers too much score compared to other kinds of contributions.

We should count at most one merge commit for each PR: that will still recognize rollup makers' contributions, also guaranteeing bors will have the first place most of the times.

**Comment by Mark-Simulacrum** [comment]
I've landed some changes that should fix the bug here, so I'm going to close this. Namely, we no longer count the author of rollup merge commits, but we will count `r=` and merges on other repositories for the "contributions" column (renamed from "commits"). This means that the rollup PR itself is counted for it's author only once (presuming they `r+` it).
